# Generated by Django 5.2.8 on 2025-11-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ausgaben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausgaben_höhe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ausgaben_kategorie', models.CharField(max_length=100)),
                ('zeitpunkt_ausgabe', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
