# Generated by Django 5.2.8 on 2025-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausgaben_höhe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ausgaben_kategorie', models.CharField(max_length=100)),
                ('zeitpunkt_ausgabe', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ausgabe',
                'verbose_name_plural': 'Ausgaben',
            },
        ),
        migrations.DeleteModel(
            name='Ausgaben',
        ),
    ]
