# Generated by Django 5.2.8 on 2025-11-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ausgabe_delete_ausgaben'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapital', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
