# Generated by Django 5.2.8 on 2025-11-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_kapital'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausgabe',
            name='ausgaben_eigen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='ausgaben_kommentar',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
