# Generated by Django 5.2.8 on 2025-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kosten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kosten_kategorie', models.CharField(max_length=100)),
                ('kosten_name', models.CharField(max_length=100)),
                ('kosten_höhe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kosten_Summe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kosten_gesamt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
