# Generated by Django 5.2.8 on 2025-11-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einnahmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('einnahmen_kategorie', models.CharField(max_length=100)),
                ('einnahmen_name', models.CharField(max_length=100)),
                ('einnahmen_höhe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Einnahmen_Summe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('einnahmen_gesamt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
