# Generated by Django 5.2.8 on 2025-11-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosten', '0002_einnahmen_einnahmen_summe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restwert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restwert', models.DecimalField(decimal_places=2, default=2, max_digits=10)),
            ],
        ),
    ]
