# Generated by Django 5.2.8 on 2025-11-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosten', '0003_restwert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restwert',
            name='restwert',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
